services:
  auth_api:
    container_name: auth_api
    build:
      context: .
      dockerfile: auth_api/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - todolist_backend
    volumes:
      - auth_api_data:/app/auth_api/data/db
    develop:
      watch:
        - action: sync
          path: ./auth_api
          target: /app
          ignore:
            - .venv/

  users_api:
    container_name: users_api
    depends_on:
      - auth_api
    build:
      context: .
      dockerfile: users_api/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8000"
    networks:
      - todolist_backend
    volumes:
      - users_api_data:/app/users_api/data/db
    develop:
      watch:
        - action: sync
          path: ./users_api
          target: /app
          ignore:
            - .venv/

  todo_api:
    container_name: todo_api
    depends_on:
      - users_api
    build:
      context: .
      dockerfile: todo_api/Dockerfile
    env_file:
      - .env
    ports:
      - "8002:8000"
    networks:
      - todolist_backend
    volumes:
      - todo_api_data:/app/todo_api/data/db
    develop:
      watch:
        - action: sync
          path: ./users_api
          target: /app
          ignore:
            - .venv/

networks:
  todolist_backend:
    driver: bridge

volumes:
  auth_api_data:
  users_api_data:
  todo_api_data:
