services:
  redis_global_cache:
    container_name: redis_global_cache
    image: redis:8.4-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - todolist_backend

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # dashboard
    networks:
      - todolist_backend

  # Create the exchanges at startup here to avoid IaC.
  rabbitmq-setup:
    image: rabbitmq:4-management-alpine
    depends_on:
      - rabbitmq
    networks:
      - todolist_backend
    command: >
      sh -c "until rabbitmqadmin -u guest -p guest -H rabbitmq list vhosts; do sleep 1; done &&
             echo $'\\nCreating RabbitMQ exchanges...'
             rabbitmqadmin -u guest -p guest -H rabbitmq declare exchange name=user_credentials type=topic durable=false &&
             rabbitmqadmin -u guest -p guest -H rabbitmq declare exchange name=users type=topic durable=false &&
             echo $'\\nDone'"

  auth_api:
    container_name: auth_api
    depends_on:
      - redis_global_cache
      - rabbitmq-setup
    build:
      context: .
      dockerfile: auth_api/Dockerfile.debug
    env_file:
      - .env
    ports:
      - "8000:8000"
      - 5678:5678
    networks:
      - todolist_backend
    volumes:
      - auth_api_data:/app/auth_api/data/db
    develop:
      watch:
        - action: sync
          path: ./auth_api
          target: /app
          ignore:
            - .venv/

  users_api:
    container_name: users_api
    depends_on:
      - auth_api
      - redis_global_cache
    build:
      context: .
      dockerfile: users_api/Dockerfile.debug
    env_file:
      - .env
    ports:
      - "8001:8000"
      - 5679:5678
    networks:
      - todolist_backend
    volumes:
      - users_api_data:/app/users_api/data/db
    develop:
      watch:
        - action: sync
          path: ./users_api
          target: /app
          ignore:
            - .venv/

  todo_api:
    container_name: todo_api
    depends_on:
      - users_api
      - rabbitmq-setup
    build:
      context: .
      dockerfile: todo_api/Dockerfile.debug
    env_file:
      - .env
    ports:
      - "8002:8000"
      - 5680:5678
    networks:
      - todolist_backend
    volumes:
      - todo_api_data:/app/todo_api/data/db
    develop:
      watch:
        - action: sync
          path: ./todo_api
          target: /app
          ignore:
            - .venv/

networks:
  todolist_backend:
    driver: bridge

volumes:
  auth_api_data:
  users_api_data:
  todo_api_data:
